/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.company.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StudentInfo service. Represents a row in the &quot;asif_StudentInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.company.service.model.impl.StudentInfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.company.service.model.impl.StudentInfoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentInfo
 * @generated
 */
@ProviderType
public interface StudentInfoModel extends BaseModel<StudentInfo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student info model instance should use the {@link StudentInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this student info.
	 *
	 * @return the primary key of this student info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student info.
	 *
	 * @param primaryKey the primary key of this student info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this student info.
	 *
	 * @return the student ID of this student info
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student info.
	 *
	 * @param studentId the student ID of this student info
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the firstname of this student info.
	 *
	 * @return the firstname of this student info
	 */
	@AutoEscape
	public String getFirstname();

	/**
	 * Sets the firstname of this student info.
	 *
	 * @param firstname the firstname of this student info
	 */
	public void setFirstname(String firstname);

	/**
	 * Returns the lastname of this student info.
	 *
	 * @return the lastname of this student info
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this student info.
	 *
	 * @param lastname the lastname of this student info
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the gender of this student info.
	 *
	 * @return the gender of this student info
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this student info.
	 *
	 * @param gender the gender of this student info
	 */
	public void setGender(String gender);

	/**
	 * Returns the dateofbirth of this student info.
	 *
	 * @return the dateofbirth of this student info
	 */
	@AutoEscape
	public String getDateofbirth();

	/**
	 * Sets the dateofbirth of this student info.
	 *
	 * @param dateofbirth the dateofbirth of this student info
	 */
	public void setDateofbirth(String dateofbirth);

	/**
	 * Returns the course of this student info.
	 *
	 * @return the course of this student info
	 */
	@AutoEscape
	public String getCourse();

	/**
	 * Sets the course of this student info.
	 *
	 * @param course the course of this student info
	 */
	public void setCourse(String course);

	/**
	 * Returns the intake of this student info.
	 *
	 * @return the intake of this student info
	 */
	@AutoEscape
	public String getIntake();

	/**
	 * Sets the intake of this student info.
	 *
	 * @param intake the intake of this student info
	 */
	public void setIntake(String intake);

	/**
	 * Returns the address of this student info.
	 *
	 * @return the address of this student info
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this student info.
	 *
	 * @param address the address of this student info
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this student info.
	 *
	 * @return the city of this student info
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this student info.
	 *
	 * @param city the city of this student info
	 */
	public void setCity(String city);

	/**
	 * Returns the postcode of this student info.
	 *
	 * @return the postcode of this student info
	 */
	@AutoEscape
	public String getPostcode();

	/**
	 * Sets the postcode of this student info.
	 *
	 * @param postcode the postcode of this student info
	 */
	public void setPostcode(String postcode);

	/**
	 * Returns the country of this student info.
	 *
	 * @return the country of this student info
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this student info.
	 *
	 * @param country the country of this student info
	 */
	public void setCountry(String country);

	/**
	 * Returns the email of this student info.
	 *
	 * @return the email of this student info
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this student info.
	 *
	 * @param email the email of this student info
	 */
	public void setEmail(String email);

	/**
	 * Returns the mobile of this student info.
	 *
	 * @return the mobile of this student info
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this student info.
	 *
	 * @param mobile the mobile of this student info
	 */
	public void setMobile(String mobile);

}